/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 reg-kangaroo.glb --verbose 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/reg-kangaroo.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_1_7_0_Inside.geometry} material={materials['Mat_0.001']} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_1_7_0_Inside_1.geometry} material={materials.Mat_1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_8_4_0_Inside.geometry} material={materials['Mat_0.001']} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_8_4_0_Inside_1.geometry} material={materials.Mat_1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_0_6_0_Outside001.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_0_6_0_Outside001_1.geometry} material={materials['Mat_0.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_7_10_0_Outside001.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_7_10_0_Outside001_1.geometry} material={materials['Mat_0.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_2_0_0_Inside.geometry} material={materials['Mat_0.001']} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_2_0_0_Inside_1.geometry} material={materials.Mat_1} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_2_1_0_Outside001.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_2_1_0_Outside001_1.geometry} material={materials['Mat_0.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_4_2_0_Outside001.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_4_2_0_Outside001_1.geometry} material={materials['Mat_0.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_4_3_0_Outside001.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_4_3_0_Outside001_1.geometry} material={materials['Mat_0.001']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Design_Piece_mat_Shape_6_11_0_Inside.geometry} material={materials['Mat_0.001']} />
        <mesh geometry={nodes.Design_Piece_mat_Shape_6_11_0_Inside_1.geometry} material={materials.Mat_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/reg-kangaroo.glb')
