export const keyValueLists = {
  hoodie: {
    "hood-highpoly": "Hood",
    "left-cuff": "Left Cuff",
    "right-cuff": "Right Cuff",
    "left-sleeve": "Left Sleeve",
    "right-sleeve": "Right Sleeve",
    "reg-fp-back-body": "Back Body",
    "reg-fp-front-body": "Front Body",
    "reg-fp-bottom-band": "Body Band",
    "reg-fp-body-pocket": "Front Pocket",
    "reg-sp-back": "Back Body",
    "reg-sp-front": "Front Body",
    "reg-sp-band": "Body Band",
    "reg-sp-left-pocket": "Left Pocket",
    "reg-sp-right-pocket": "Right Pocket",
    "crop-fp-back": "Back Body",
    "crop-fp-front": "Front Body",
    "crop-fp-bottom": "Body Band",
    "crop-fp-pocket": "Front Pocket",
    "crop-np-back": "Back Body",
    "crop-np-front": "Front Body",
    "crop-np-bottom": "Body Band",
    "crop-sp-back": "Back Body",
    "crop-sp-front": "Front Body",
    "crop-sp-bottom": "Body Band",
    "crop-sp-left-pocket": "Left Pocket",
    "crop-sp-right-pocket": "Right Pocket",
  },
  polo: {
    "collar": "Collar",
    "button-one_2": "Button 2",
    "button-two_2": "Button 1",
    "long-sleeve-right-sleeve": "Right Sleeve",
    "long-sleeve-left-sleeve": "Left Sleeve",
    "long-sleeve-right-cuff": "Right Cuff",
    "long-sleeve-left-cuff": "Left Cuff",
    "short-sleeve-right": "Right Sleeve",
    "short-sleeve-left": "Left Sleeve",
    "crop-body-front": "Front Body",
    "crop-body-back": "Back Body",
    "crop-body-band": "Body Band",
    "reg-body_front": "Front Body",
    "reg-body_back": "Back Body",
    "reg-body_band": "Body Band",
  },
};
